disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Lukas Scarfe"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/logo2.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Lukas Scarfe"
  email = "lukasscarfe@gmail.com"
  image = "img/Lukas_Scarfe_Headshot_small.png"
  imageQuality = 96
  headline = "B. Eng in Engineering Physics, M. Sc in Physics"
  bio = "Lukas Scarfe PhD Student in Physics at the University of Ottawa."
  links = [
    { email = "mailto:lukasscarfe+website@gmail.com" },
    { "google-scholar" = "https://scholar.google.com/citations?user=_eBW18oAAAAJ&hl=en&oi=ao" },
    { github = "https://github.com/lukasscarfe" },
    { linkedin = "https://www.linkedin.com/in/lukas-scarfe-0216b4190/" },
    { researchgate = "https://www.researchgate.net/profile/Lukas-Scarfe" },
    { orcid = "https://orcid.org/0009-0000-4110-8817" }
    # { youtube = "https://youtube.com/username" }
  ]
